### ISSUE TITLE
bug: shorthand for `top` not working

### ISSUE THREAD

**Issue by HLasse** [MartinBernstorff/lumberman#261]
According to the help, the shorthand for top is `to`
<img width="128" alt="image" src="https://github.com/MartinBernstorff/lumberman/assets/23191638/5f024f95-9899-452d-8349-39494a10b4f1">

However, running e.g. `lm i to` gives the following error
<img width="852" alt="image" src="https://github.com/MartinBernstorff/lumberman/assets/23191638/e1219960-b140-4e9f-a5ee-64bec28c2e92">

**Comment by MartinBernstorff** [comment]
Thanks for the report! Will take a look.
